# Generated by Django 5.2.5 on 2025-11-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_shippingmethod_order_shipping_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='qr_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_client_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria'), ('mobile_payment', 'Pago Móvil'), ('check', 'Cheque'), ('store_credit', 'Crédito de Tienda'), ('stripe', 'Stripe (Tarjeta)'), ('qr_code', 'Código QR')], max_length=20),
        ),
    ]
