# Generated by Django 5.2.5 on 2025-11-10 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_qr_code_data_payment_qr_image_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('partially_paid', 'Parcialmente Pagado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_by_id',
            field=models.CharField(blank=True, help_text='Documento de identidad', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picked_up_by_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_code',
            field=models.CharField(blank=True, help_text='Código de 6 dígitos para retiro', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('processing', 'Procesando'), ('ready_for_pickup', 'Listo para Retiro'), ('picked_up', 'Retirado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
