# Generated by Django 5.2.5 on 2025-11-10 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resend_api_key', models.CharField(blank=True, max_length=200)),
                ('from_email', models.EmailField(default='noreply@sportswear.com', max_length=254)),
                ('from_name', models.CharField(default='SPORTSWEAR', max_length=100)),
                ('admin_email', models.EmailField(help_text='Email del administrador para reportes', max_length=254)),
                ('enable_order_confirmation', models.BooleanField(default=True, verbose_name='Confirmar Órdenes')),
                ('enable_payment_notifications', models.BooleanField(default=True, verbose_name='Notificar Pagos')),
                ('enable_low_stock_alerts', models.BooleanField(default=True, verbose_name='Alertas de Stock Bajo')),
                ('enable_daily_reports', models.BooleanField(default=True, verbose_name='Reportes Diarios')),
                ('daily_report_time', models.TimeField(default='20:00:00', help_text='Hora para enviar reporte diario (24h)')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Cantidad mínima antes de alertar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Notificaciones',
                'verbose_name_plural': 'Configuración de Notificaciones',
                'db_table': 'notification_settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('order_created', 'Confirmación de Compra'), ('payment_received', 'Cuota Pagada'), ('payment_reminder', 'Recordatorio de Pago'), ('low_stock', 'Stock Bajo'), ('daily_sales_report', 'Reporte Diario de Ventas')], max_length=50, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('html_template', models.TextField(help_text='HTML template con placeholders: {{variable}}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Notificación',
                'verbose_name_plural': 'Plantillas de Notificaciones',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('system', 'Sistema')], default='system', max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email_id', models.CharField(blank=True, help_text='ID del email en Resend', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sent', 'Enviado'), ('failed', 'Fallido'), ('read', 'Leído')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Datos adicionales en JSON')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_8ab96f_idx'), models.Index(fields=['event_type'], name='notificatio_event_t_4343b6_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx')],
            },
        ),
    ]
