#!/bin/bash
# Script para ejecutar migraciones en Cloud Run

echo "🔧 Ejecutando migraciones en Cloud Run..."
echo "=========================================="

# Obtener la URL del servicio
SERVICE_URL="https://ecommerce-backend-930184937279.us-central1.run.app"

echo ""
echo "📊 Probando conectividad del backend..."
curl -s "$SERVICE_URL/api/" | head -20

echo ""
echo ""
echo "=========================================="
echo "Para ejecutar migraciones manualmente:"
echo "=========================================="
echo ""
echo "Opción 1: Usar Cloud Run Jobs (Recomendado)"
echo "---------------------------------------------"
echo "gcloud run jobs create migrate-db \\"
echo "  --image us-central1-docker.pkg.dev/big-axiom-474503-m5/ecommerce-registry/backend:latest \\"
echo "  --region us-central1 \\"
echo "  --set-cloudsql-instances big-axiom-474503-m5:us-central1:myproject-db \\"
echo "  --set-env-vars DB_NAME=ecommerce \\"
echo "  --set-env-vars DB_USER=prueba \\"
echo "  --set-env-vars DB_PASSWORD=prueba123secure \\"
echo '  --set-env-vars DB_HOST=/cloudsql/big-axiom-474503-m5:us-central1:myproject-db \\'
echo "  --set-env-vars DB_PORT=5432 \\"
echo "  --command python \\"
echo "  --args manage.py,migrate,--noinput"
echo ""
echo "gcloud run jobs execute migrate-db --region us-central1 --wait"
echo ""
echo ""
echo "Opción 2: Ejecutar comando en una instancia activa"
echo "---------------------------------------------------"
echo "gcloud run services update ecommerce-backend \\"
echo "  --region us-central1 \\"
echo "  --min-instances 1"
echo ""
echo "# Esperar que la instancia esté activa, luego:"
echo "gcloud run services proxy ecommerce-backend \\"
echo "  --region us-central1 \\"
echo "  --port 8080"
echo ""
echo ""
echo "Opción 3: Forzar restart del servicio (ejecutará el entrypoint)"
echo "---------------------------------------------------------------"
echo "gcloud run services update ecommerce-backend \\"
echo "  --region us-central1 \\"
echo "  --set-env-vars FORCE_MIGRATE=true"
echo ""
