# Generated by Django 5.2.5 on 2025-11-10 13:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=20)),
                ('initial_cash', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo inicial en caja', max_digits=10)),
                ('final_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo final contado', max_digits=10, null=True)),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='Efectivo esperado según ventas', max_digits=10)),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre esperado y real', max_digits=10)),
                ('sales_count', models.IntegerField(default=0, help_text='Número de ventas realizadas')),
                ('total_cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_qr_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cashier_shifts', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_shifts', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='employees.employee')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['cashier', 'start_time'], name='employees_s_cashier_49ef4a_idx'), models.Index(fields=['status'], name='employees_s_status_fc77d2_idx'), models.Index(fields=['start_time'], name='employees_s_start_t_5d20e3_idx')],
            },
        ),
    ]
