# Generated by Django 5.2.6 on 2025-10-08 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('report_type', models.CharField(choices=[('list', 'Lista/Tabla'), ('chart', 'Gráfico'), ('summary', 'Resumen'), ('comparison', 'Comparativo'), ('timeline', 'Línea de Tiempo')], max_length=20, verbose_name='Tipo de Reporte')),
                ('fields', models.JSONField(default=list, verbose_name='Campos a Mostrar')),
                ('filters', models.JSONField(default=dict, verbose_name='Filtros')),
                ('ordering', models.JSONField(default=list, verbose_name='Ordenamiento')),
                ('grouping', models.JSONField(default=list, verbose_name='Agrupación')),
                ('aggregations', models.JSONField(default=dict, verbose_name='Agregaciones')),
                ('layout_config', models.JSONField(default=dict, verbose_name='Configuración de Layout')),
                ('chart_config', models.JSONField(default=dict, verbose_name='Configuración de Gráficos')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('is_system', models.BooleanField(default=False, verbose_name='Reporte del Sistema')),
                ('allowed_exports', models.JSONField(default=list, verbose_name='Formatos de Exportación')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo Base')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenant.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Plantilla de Reporte',
                'verbose_name_plural': 'Plantillas de Reportes',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(default=dict, verbose_name='Parámetros')),
                ('filters_applied', models.JSONField(default=dict, verbose_name='Filtros Aplicados')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Iniciado')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('result_count', models.IntegerField(blank=True, null=True, verbose_name='Número de Registros')),
                ('result_data', models.JSONField(default=dict, verbose_name='Datos del Resultado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdf/', verbose_name='Archivo PDF')),
                ('excel_file', models.FileField(blank=True, upload_to='reports/excel/', verbose_name='Archivo Excel')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ejecutado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenant.tenant', verbose_name='Empresa')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Plantilla')),
            ],
            options={
                'verbose_name': 'Ejecución de Reporte',
                'verbose_name_plural': 'Ejecuciones de Reportes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Widget')),
                ('widget_type', models.CharField(choices=[('metric', 'Métrica'), ('chart', 'Gráfico'), ('table', 'Tabla'), ('progress', 'Barra de Progreso'), ('gauge', 'Medidor'), ('calendar', 'Calendario'), ('map', 'Mapa')], max_length=20, verbose_name='Tipo de Widget')),
                ('config', models.JSONField(default=dict, verbose_name='Configuración')),
                ('refresh_interval', models.IntegerField(default=300, verbose_name='Intervalo de Actualización (segundos)')),
                ('position_x', models.IntegerField(default=0, verbose_name='Posición X')),
                ('position_y', models.IntegerField(default=0, verbose_name='Posición Y')),
                ('width', models.IntegerField(default=4, verbose_name='Ancho')),
                ('height', models.IntegerField(default=3, verbose_name='Alto')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenant.tenant', verbose_name='Empresa')),
                ('visible_to_groups', models.ManyToManyField(blank=True, related_name='dashboard_widgets', to='accounts.tenantgroup', verbose_name='Visible para Grupos')),
                ('visible_to_users', models.ManyToManyField(blank=True, related_name='visible_widgets', to=settings.AUTH_USER_MODEL, verbose_name='Visible para Usuarios')),
                ('report_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.reporttemplate', verbose_name='Plantilla de Reporte')),
            ],
            options={
                'verbose_name': 'Widget de Dashboard',
                'verbose_name_plural': 'Widgets de Dashboard',
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Filtro')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('filter_config', models.JSONField(default=dict, verbose_name='Configuración del Filtro')),
                ('is_public', models.BooleanField(default=False, verbose_name='Público')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Modelo')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenant.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Filtro Guardado',
                'verbose_name_plural': 'Filtros Guardados',
                'unique_together': {('tenant', 'name', 'content_type')},
            },
        ),
    ]
