# Generated by Django 5.2.6 on 2025-10-19 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0001_initial'),
        ('tenant', '0011_tenant_default_warehouse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Modelo')),
                ('app_label', models.CharField(max_length=100, verbose_name='App')),
                ('model_name', models.CharField(max_length=100, verbose_name='Modelo')),
                ('available_fields', models.JSONField(default=dict, verbose_name='Campos Disponibles')),
                ('related_models', models.JSONField(default=list, verbose_name='Modelos Relacionados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('display_order', models.IntegerField(default=0, verbose_name='Orden de Visualización')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenant.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Modelo Disponible para Reportes',
                'verbose_name_plural': 'Modelos Disponibles para Reportes',
                'ordering': ['display_order', 'name'],
                'unique_together': {('tenant', 'app_label', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Reporte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('selected_fields', models.JSONField(default=list, verbose_name='Campos Seleccionados')),
                ('filters', models.JSONField(default=list, verbose_name='Filtros')),
                ('ordering', models.JSONField(default=list, verbose_name='Ordenamiento')),
                ('grouping', models.JSONField(default=list, verbose_name='Agrupación')),
                ('aggregations', models.JSONField(default=dict, verbose_name='Agregaciones')),
                ('show_totals', models.BooleanField(default=False, verbose_name='Mostrar Totales')),
                ('page_size', models.IntegerField(default=50, verbose_name='Registros por Página')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Compartido')),
                ('execution_count', models.IntegerField(default=0, verbose_name='Veces Ejecutado')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Ejecución')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_reports', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('report_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.availablereportmodel', verbose_name='Modelo del Reporte')),
                ('shared_with', models.ManyToManyField(blank=True, related_name='shared_reports', to=settings.AUTH_USER_MODEL, verbose_name='Compartido con')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='tenant.tenant', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Reporte Guardado del Usuario',
                'verbose_name_plural': 'Reportes Guardados de Usuarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
