# Generated by Django 5.2.5 on 2025-10-17 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('sales', 'Ventas'), ('purchases', 'Compras'), ('inventory', 'Inventario'), ('customers', 'Clientes'), ('financial', 'Financiero'), ('custom', 'Personalizado')], max_length=20)),
                ('input_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio')], max_length=10)),
                ('original_prompt', models.TextField(help_text='Prompt original del usuario')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='reports/audio/')),
                ('transcription', models.TextField(blank=True, help_text='Transcripción del audio', null=True)),
                ('generated_sql', models.TextField(help_text='SQL generado por la IA')),
                ('sql_params', models.JSONField(blank=True, default=dict)),
                ('results_count', models.IntegerField(default=0)),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('json', 'JSON')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('execution_time', models.FloatField(help_text='Tiempo de ejecución en segundos')),
                ('tokens_used', models.IntegerField(default=0, help_text='Tokens consumidos en la IA')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='reports_rep_user_id_f42065_idx'), models.Index(fields=['report_type'], name='reports_rep_report__bbfb2b_idx')],
            },
        ),
    ]
