# Generated by Django 4.2.7 on 2025-09-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_passwordresettoken_emailverificationtoken'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='custom_auth_user',
        ),
    ]
